package:
  name: menpobench
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pathlib 1.0  # [py2k]
    - menpofit 0.2.*
    - pyyaml 3.*
    - docopt 0.6.*
    - pyrx 0.3.*
    - tinys3 0.1.*


test:

  requires:
    - nose

  imports:
    - menpobench

about:
  home: https://github.com/menpo/menpobench/
  license: BSD License
